name = "myself-bbs"
main = "dist/worker.js"
account_id = "4d3e1d6fb1c54dd55148a84a4ccc21ff"
workers_dev = true
kv_namespaces = []
compatibility_date = "2022-06-01"

[build]
command = "npm run -s build"

[[rules]]
type = "ESModule"
globs = ["src/**/*.js"]
